import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./component/Navbar";
import CustomSessionProvider from "./provider/SessionProvider";
export const metadata: Metadata = {
  title: "Find your event",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CustomSessionProvider>
          <Navbar />
          {children}
        </CustomSessionProvider>
      </body>
    </html>
  );
}
